### ISSUE TITLE
Negative dimension size error with Conv2D when using KB6 drum samples

### ISSUE THREAD

**Issue by kasbah** [drscotthawley/panotti#2]
Hey, thanks very much for this work. I am just dabbling in machine learning a bit so may be doing something very stupid. 

1. I downloaded [drum samples from KB6](http://samples.kb6.de/downloads.php) and am trying to classify them into `snare` or `kick`. 
2. I padded them with silence to all be the same length and made them all mono
3. I ran `./preprocess_data.py`
4. When I run `./train_network.py` I run into this error:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 3 from 1 for 'Conv2D' (op: 'Conv2D') with input shapes: [?,1,96,924], [3,3,924,32].
```

<details>

```
Using TensorFlow backend.
class_names =  ['kick', 'snare']
total files =  16 , going to load total_load =  16
   get_sample_dimensions: Access__Access_Virus_-_TI__Access_Virus_TI_-_Cyberworm__BassDrum_01_padded.wav.npy: melgram.shape =  (1, 1, 96, 924)
 melgram dimensions:  (1, 1, 96, 924)

 Loading class 1/2: 'kick', File 1/8: Preproc/Train/kick/Access__Access_Virus_-_TI__ Loading class 1/2: 'kick', File 8/8: Preproc/Train/kick/Access__Access_Virus_-_B__BassDrum_01_padded.wav.npy                  
 Loading class 2/2: 'snare', File 1/8: Preproc/Train/snare/Akai__Akai_MPC500__4._Too Loading class 2/2: 'snare', File 8/8: Preproc/Train/snare/Access__Access_Virus_-_TI__Access_Virus_TI_-_Cyberworm__Snare01_padded.wav.npy                  
Looking for previous weights...
No weights file detected, so starting from scratch.
Making Keras 1 version of model
 MyCNN: X.shape =  (16, 1, 96, 924) , channels =  1
Traceback (most recent call last):
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 3 from 1 for 'Conv2D' (op: 'Conv2D') with input shapes: [?,1,96,924], [3,3,924,32].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train_network.py", line 59, in <module>
    train_network(weights_file=args.weights, classpath=args.classpath)
  File "./train_network.py", line 31, in train_network
    model = make_model(X_train, class_names, no_cp_fatal=False, weights_file=weights_file)
  File "/home/kaspar.emanuel/drums/panotti/panotti/models.py", line 125, in make_model
    model = MyCNN(X, nb_classes=len(class_names), nb_layers=nb_layers)
  File "/home/kaspar.emanuel/drums/panotti/panotti/models.py", line 44, in MyCNN
    border_mode='valid', input_shape=input_shape))
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/keras/models.py", line 299, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/keras/engine/topology.py", line 401, in create_input_layer
    self(x)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/keras/layers/convolutional.py", line 475, in call
    filter_shape=self.W_shape)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2691, in conv2d
    x = tf.nn.conv2d(x, kernel, strides, padding=padding)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 631, in conv2d
    data_format=data_format, name=name)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/kaspar.emanuel/drums/panotti/venv3/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 3 from 1 for 'Conv2D' (op: 'Conv2D') with input shapes: [?,1,96,924], [3,3,924,32].

```

</details>

---

[Here is a sample set of just 10 samples for each category](https://cloud.monostable.co.uk/drum-Samples.zip) if you would like to try and reproduce the error quickly. 

I tried it with audio-classifier-keras-cnn and Python2 as well but run into the same error. I am just running the Physionet example to see what that does but it will take a while to do the preprocessing (I didn't want to change anything in case that causes errors).

**Comment by kasbah** [comment]
Looks like this was an issue with using an older Keras. `pip install keras==2.1.2` solved this issue. Maybe that should go into the `requirements.txt`?

**Comment by drscotthawley** [comment]
Thanks for pointing that out, as well as providing the fix!    Yes, I'd upgraded my code to Keras 2 but forgot to change requirements.txt.   I've now made the change you suggested.
